substitutions:
  devicename: aerotermia
  description: "Midea M-Theri Ultimate"

packages:
  extra_diagnostics: !include midea/64_extra_diagnostics.yaml
  base: !include midea/00_base.yaml
  modbus: !include midea/10_modbus.yaml
  controls: !include midea/30_controls.yaml
  switches: !include midea/40_switches.yaml
  sensors_temperatures: !include midea/60_temperatures.yaml
  sensors_water: !include midea/61_water.yaml
  sensors_compressor: !include midea/62_compressor.yaml
  sensors_energy: !include midea/63_energy.yaml
  binary_sensors: !include midea/70_binary_sensors.yaml
  text_sensors: !include midea/80_text_sensors.yaml
  pressure: !include midea/90_pressure.yaml
  cop: !include midea/91_cop.yaml
  climate_curve: !include midea/92_climate_curve.yaml
  raw_registers: !include midea/99_raw_registers.yaml
