# ==================================================
# 90_PRESSURE
# ==================================================
# Sensor de presión analógico de caldera vieja.
#
# Sensor:
# - Alimentación: 8.5-30 VDC, recomendado 24 VDC
# - Salida: 0.5-4.25 V
# - Rango: 0-5 bar
#
# Cableado:
# Rojo  -> +24 V
# Negro -> GND fuente 24 V y GND ESP32 común
# Azul  -> divisor resistivo -> GPIO34
#
# Divisor:
# Azul sensor -> 10 kΩ -> GPIO34 -> 20 kΩ -> GND
#
# Calibración:
# reloj 2.00 bar -> lectura previa 1.82 bar
# reloj 2.65 bar -> lectura previa 2.43 bar

sensor:
  - platform: adc
    pin: GPIO34
    name: "Presión circuito calefacción"
    id: "${devicename}_presion_circuito_calefaccion"
    icon: mdi:gauge
    attenuation: 12db
    update_interval: 10s
    unit_of_measurement: "bar"
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 2  
    filters:
      - calibrate_linear:
          - 0.45 -> 0.0
          - 0.95 -> 0.5
          - 1.20 -> 1.0
          - 1.50 -> 1.5
          - 2.00 -> 2.0
          - 2.32 -> 2.5
      - clamp:
          min_value: 0.0
          max_value: 5.
