# ==================================================
# 60_TEMPERATURES
# ==================================================

sensor:
  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "Temperatura retorno agua"
    id: "${devicename}_temperatura_retorno_agua"
    icon: mdi:thermometer-chevron-down
    register_type: holding
    address: 0x68
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "Temperatura impulsión agua"
    id: "${devicename}_temperatura_impulsion_agua"
    icon: mdi:thermometer-chevron-up
    register_type: holding
    address: 0x69
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "Temperatura exterior"
    id: "${devicename}_temperatura_exterior"
    icon: mdi:sun-thermometer
    register_type: holding
    address: 0x6B
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "Temperatura descarga compresor"
    id: "${devicename}_temperatura_descarga_compresor"
    icon: mdi:thermometer-high
    register_type: holding
    address: 0x6C
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "Temperatura depósito ACS"
    id: "${devicename}_temperatura_deposito_acs"
    icon: mdi:water-thermometer
    register_type: holding
    address: 0x73
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
